### ISSUE TITLE
Adicionar opção para número máximo de tentativas por CNPJ

### ISSUE THREAD

**Issue by rhuanbarreto** [leads2b/receita-tools#24]
Para os seguintes CNPJs a consulta está dando timeout.

"86.700.390/0001-28"
"04.463.276/0019-96"
"03.052.564/0008-32"
"25.526.428/0001-01"
"96.513.486/0005-64"
"25.058.001/0001-18"
"24.122.924/0001-29"
"64.948.656/0001-13"
"26.292.303/0001-19"
"23.119.588/0001-00"
"21.339.965/0020-46"
"92.753.268/0001-12"
"46.100.426/0001-18"
"03.324.310/0001-50"
"11.149.881/0002-04"
"22.572.616/0001-70"
"13.526.884/0001-64"
"10.722.866/0001-60"
"24.185.522/0004-16"
"22.940.725/0001-00"
"23.150.886/0001-55"
"33.182.809/0074-96"
"21.783.963/0001-89"
"21.808.713/0001-56"
"11.801.379/0001-55"
"26.416.041/0001-57"
"01.542.714/0004-37"
"23.469.656/0001-53"
"24.399.002/0001-63"
"24.345.616/0001-62"
"26.210.561/0001-09"
"03.584.647/0007-91"
"24.281.509/0001-18"
"15.752.002/0001-04"
"08.506.545/0001-86"
"26.622.435/0001-61"
"26.391.097/0001-02"
"07.498.009/0004-66"
"26.043.053/0001-83"
"26.153.473/0001-12"
"28.152.650/0083-18"
"00.903.166/0004-60"
"08.470.309/0002-38"
"16.492.411/0002-62"
"02.693.750/0056-95"
"07.480.811/0007-71"
"80.378.052/0004-88"
"19.486.258/0001-78"
"58.034.315/0005-63"
"29.884.632/0008-13"
"33.112.152/0036-65"
"33.112.152/0028-55"
"21.303.715/0001-93"
"03.948.423/0001-26"
"17.712.475/0001-03"
"26.387.277/0001-02"
"15.691.731/0001-06"
"62.545.686/0016-30"
"04.192.552/0002-80"
"03.138.061/0003-70"
"21.203.157/0001-94"
"32.319.931/0038-35"
"18.597.384/0001-37"
"04.070.135/0001-84"
"24.750.649/0001-98"
"21.961.168/0001-33"
"77.679.686/0001-13"
"15.702.040/0001-52"
"02.430.739/0001-69"
"19.659.983/0001-09"
"18.599.044/0001-45"
"39.692.108/0001-28"
"24.117.690/0001-21"
"16.957.047/0001-88"
"21.069.291/0001-44"
"78.559.440/0005-02"
"33.112.152/0037-46"
"61.150.751/0037-90"
"18.416.738/0001-08"
"05.904.868/0003-00"
"01.182.204/0002-34"

**Comment by vkruoso** [comment]
Pode confirmar se está usando a API Pública ou Comercial?

**Comment by rhuanbarreto** [comment]
Pública. Estou usando o receita tools e ele fica travado em 0%

**Comment by vkruoso** [comment]
Peço que verifique nossa página de FAQ para entender melhor como o sistema funciona: https://www.receitaws.com.br/faq 

Utilizando a API Pública não existe garantia de resolução de CNPJs novos (ou seja, que não estão em nossa base de dados). O ideal neste caso é utilizar a API Comercial.

**Comment by rhuanbarreto** [comment]
Ok. Mas o receita-tools não está mostrando algum erro de timeout. Está travado. Eu que tentei esses CNPJs no site.

O receita-tools tem que ter um tempo limite pra considerar timeout da consulta e pular pro próximo da lista. Hoje ele fica aguardando eternamente a resposta da API pública.

**Comment by vkruoso** [comment]
O que o receita-tools faz é continuar tentando em caso de timeouts ou erros da API até que os dados sejam retornados com sucesso. Realmente, se estiver utilizando a API Pública é possível que o processo fique em execução por muito tempo. Note que são realizadas várias consultas em paralelo também.

Acredito que aqui podemos adicionar uma opção de tentativas máxima para um mesmo CNPJ, e uma outra opção para o número máximo de timeouts. Seria o suficiente para resolver o seu problema operacional @rhuanbarreto ?

**Comment by rhuanbarreto** [comment]
@vkruoso acredito que a questão de tentativa deveria ser do usuário e não do script. Isso evitaria flood de timeout e retry no seu servidor. O número máximo de tentativas seria 1 e o número máximo de timeouts também seria 1. Na maior parte das vezes o timeout só se resolve minutos ou horas após, o que trava a execução do script e enche seu servidor de requests que não resolveriam.

Os CNPJ que sofressem com esse problema poderiam ser reportados como Timeout na chave "error" do JSON. Assim por decisão do usuário eles seriam reenviados ao servidor num segundo comando receita-tools.

**Comment by rhuanbarreto** [comment]
mais um CNPJ com timeout. 24.350.697/0001-99. testado no site.

Você podia colocar essa opção.

**Comment by rhuanbarreto** [comment]
O erro persiste mesmo na api comercial.

**Comment by pedroig** [comment]
Utilizar a API pública para um grande volume de dados no ReceitaWS gera um bloqueio temporário do servidor. Ele passa a retornar status_code 429 de excesso de requisições a partir de um mesmo IP. Assim, o problema não se trata da ausência de garantia de resolução de CNPJs não existentes, até porque isso é fornecido na API pública conforme descrito na tabela de preços (https://www.receitaws.com.br/pricing).
