### ISSUE TITLE
consulta no delphi

### ISSUE THREAD

**Issue by thiagoamaralcaragua** [leads2b/receita-tools#34]
bom dia
no delphi eu faco uma consulpta pelo rest

 RESTRequestCNPJ.Resource := CNPJ;
  RESTRequestCNPJ.Execute;
  jsonObject := TJsonObject.ParseJSONValue(RESTResponseCNPJ.Content)
    as TJsonObject;
  Pessoa.razao := jsonObject.GetValue('nome').Value;
  Pessoa.fantasia := jsonObject.GetValue('fantasia').Value;
  Pessoa.logradouro := jsonObject.GetValue('logradouro').Value;
  Pessoa.numero := jsonObject.GetValue('numero').Value;
  Pessoa.bairro := jsonObject.GetValue('bairro').Value;
  Pessoa.municipio := jsonObject.GetValue('municipio').Value;
  Pessoa.uf := jsonObject.GetValue('uf').Value;
  Pessoa.cep := jsonObject.GetValue('cep').Value;
  Pessoa.email := jsonObject.GetValue('email').Value;
  Pessoa.complemento := jsonObject.GetValue('complemento').Value;
  Pessoa.telefone := jsonObject.GetValue('telefone').Value;
  Pessoa.cnae := jsonObject.GetValue('atividade_principal').Value;

no campo cnae trago a atividade_principal como que falo para trazer somente o code do cnae

**Comment by vkruoso** [comment]
Infelizmente não conhecemos Delphi para conseguirmos lhe dar suporte. A API retorna dados em JSON por ser comumente bem suportado em todas as linguagens. Talvez o link abaixo lhe ajude:

https://www.devmedia.com.br/forum/delphi-seattle-como-efetuar-leitura-de-arrays-em-json/583866
