### ISSUE TITLE
Não consigo trazer os dados

### ISSUE THREAD

**Issue by martineix** [leads2b/receita-tools#37]
Olá. Tudo bem?
Estou seguindo os passos mas não entendi corretamente como fazer para consultar.
Estou com a API paga, mas não consigo usar o receita-tools, após fazer o pip install. Estou fazendo pelo Jupyter Notebook

**Comment by vkruoso** [comment]
@martineix Poderia compartilhar seu notebook por gentileza?

**Comment by martineix** [comment]
Então, eu não entendi como faço para trazer os dados
Eu fiz o pip install receita-tools
Instalou, mas aí os comandos receita build, get ele não traz
Consegue me ajudar? Não sou experiente 100% em python

**Comment by vkruoso** [comment]
> Então, eu não entendi como faço para trazer os dados Eu fiz o pip install receita-tools Instalou, mas aí os comandos receita build, get ele não traz Consegue me ajudar? Não sou experiente 100% em python

Qual o comando que executou? Primeiramente é necessário fazer o `get` para baixar os dados utilizando a API:

```bash
export RWS_TOKEN="<my-token>"
receita get list.csv --output cnpj_data -d 20
```

Posteriormente é preciso rodar o comando `build`:

```bash
receita build --input cnpj_data --output results
```
